// Code generated by "stringer -type=ObjectType"; DO NOT EDIT.

package object

import "fmt"

const _ObjectType_name = "INTEGERBOOLEANNULLRETURN_VALUEERRORFUNCTIONSTRING"

var _ObjectType_index = [...]uint8{0, 7, 14, 18, 30, 35, 43, 49}

func (i ObjectType) String() string {
	i -= 1
	if i < 0 || i >= ObjectType(len(_ObjectType_index)-1) {
		return fmt.Sprintf("ObjectType(%d)", i+1)
	}
	return _ObjectType_name[_ObjectType_index[i]:_ObjectType_index[i+1]]
}
